"""Added currency column to expenses and income tables

Revision ID: 2765c93f3a54
Revises: 025bf515437d
Create Date: 2026-02-18 01:09:49.868906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2765c93f3a54'
down_revision: Union[str, Sequence[str], None] = '025bf515437d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('currency', sa.String(length=100), nullable=False))
    op.add_column('income', sa.Column('currency', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'currency')
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
