"""Added fx_rates table now, since before it wasn't added

Revision ID: 3850c001f470
Revises: bfc2cd0ec8af
Create Date: 2026-02-28 03:15:55.102454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3850c001f470'
down_revision: Union[str, Sequence[str], None] = 'bfc2cd0ec8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('original_currency', sa.String(length=100), nullable=False),
    sa.Column('to_currency', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('original_currency', 'to_currency', 'rate_date', name='uq_fx_rates_rate_date')
    )
    op.create_index(op.f('ix_fx_rates_rate_id'), 'fx_rates', ['rate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fx_rates_rate_id'), table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
