"""Added key col to insight_classes + Seeding insight class builtin categories

Revision ID: 3ffbb2ac5484
Revises: 63b6443789b6
Create Date: 2026-02-09 04:07:22.150838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffbb2ac5484'
down_revision: Union[str, Sequence[str], None] = '63b6443789b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insight_classes', sa.Column('key', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_insight_classes_key'), 'insight_classes', ['key'], unique=True)

    op.execute(
        sa.text(""" 
            INSERT INTO insight_classes (key, name, is_builtin) VALUES
                ('GAS_PRICES', 'Gas Prices', true),
                ('RENT_PRICES', 'Rent Prices', true),
                ('GLOBAL_UPDATES', 'Global Finance Updates/Concerns', true),
                ('LOCAL_UPDATES', 'Local Market Updates', true),
                ('INV_STOCK_MARKET', 'Stock Market Updates and Recommendations', true),
                ('INV_TECH', 'Tech Investment Updates and Recommendations', true),
                ('INV_SEMICONDUCTOR', 'Semiconductors Updates and Recommendations', true)
            ON CONFLICT (key) DO NOTHING;
        """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insight_classes_key'), table_name='insight_classes')
    op.drop_column('insight_classes', 'key')

    op.execute(
        sa.text(""" 
            DELETE FROM insight_classes 
            WHERE key IN (
            'GAS_PRICES',
            'RENT_PRICES',
            'GLOBAL_UPDATES',
            'LOCAL_UPDATES',
            'INV_STOCK_MARKET',
            'INV_TECH',
            'INV_SEMICONDUCTOR'
            );
        """)
    )
    # ### end Alembic commands ###
