"""Adding one active/trial subscription to subscriptions table

Revision ID: 63b6443789b6
Revises: d7c482fb6c48
Create Date: 2026-02-09 03:31:17.309682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b6443789b6'
down_revision: Union[str, Sequence[str], None] = 'd7c482fb6c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_subscriptions_one_active_or_trial_per_user",
        "subscriptions",
        ["user_id"],
        postgresql_where = sa.text("status IN ('ACTIVE', 'TRIAL')")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_subscriptions_one_active_or_trial_per_user",
        "subscriptions"
    )
    # ### end Alembic commands ###
