"""Added fx_rates table, and added fx rates to income and expense tables, and changed col name in income and expense

Revision ID: bfc2cd0ec8af
Revises: 2765c93f3a54
Create Date: 2026-02-27 23:47:30.745219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc2cd0ec8af'
down_revision: Union[str, Sequence[str], None] = '2765c93f3a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('expenses', sa.Column('fx_rate_to_usd', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('expenses', sa.Column('fx_date', sa.Date(), nullable=True))
    op.drop_column('expenses', 'preferred_currency_amount')
    op.add_column('income', sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('income', sa.Column('fx_rate_to_usd', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('income', sa.Column('fx_date', sa.Date(), nullable=True))
    op.drop_column('income', 'preferred_currency_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('preferred_currency_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('income', 'fx_date')
    op.drop_column('income', 'fx_rate_to_usd')
    op.drop_column('income', 'original_amount')
    op.add_column('expenses', sa.Column('preferred_currency_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'fx_date')
    op.drop_column('expenses', 'fx_rate_to_usd')
    op.drop_column('expenses', 'original_amount')
    # ### end Alembic commands ###
