"""Creating first version of db tables

Revision ID: d7c482fb6c48
Revises: 
Create Date: 2026-02-09 03:22:51.465658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7c482fb6c48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_classes',
    sa.Column('insight_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('insight_class_id')
    )
    op.create_index(op.f('ix_insight_classes_insight_class_id'), 'insight_classes', ['insight_class_id'], unique=False)
    op.create_index(op.f('ix_insight_classes_name'), 'insight_classes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('preferred_currency', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('stripe_created_ts', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', name='webhook_status'), server_default='RECEIVED', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_type'), 'webhook_events', ['type'], unique=False)
    op.create_table('billing_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_billing_customers_id'), 'billing_customers', ['id'], unique=False)
    op.create_table('forecasts',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index(op.f('ix_forecasts_forecast_id'), 'forecasts', ['forecast_id'], unique=False)
    op.create_table('insights',
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('insight_class_id', sa.Integer(), nullable=False),
    sa.Column('raw_tool_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['insight_class_id'], ['insight_classes.insight_class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_index(op.f('ix_insights_insight_id'), 'insights', ['insight_id'], unique=False)
    op.create_table('recurrence_series',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_type', sa.Enum('EXPENSE', 'INCOME', name='series_type'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency'), server_default=sa.text("'MONTHLY'"), nullable=False),
    sa.Column('bulk', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("(bulk = false) OR (frequency IN ('MONTHLY','YEARLY'))", name='ck_series_bulk_frequency'),
    sa.CheckConstraint('(end_date IS NULL) OR (end_date >= start_date)', name='ck_series_end_after_start'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index(op.f('ix_recurrence_series_series_id'), 'recurrence_series', ['series_id'], unique=False)
    op.create_table('user_insight_prefs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_class_id', sa.Integer(), nullable=False),
    sa.Column('enable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['insight_class_id'], ['insight_classes.insight_class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'insight_class_id')
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bulk', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expense_category', sa.String(length=255), nullable=False),
    sa.Column('preferred_currency_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('usd_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recurrence_series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recurrence_series_id'], ['recurrence_series.series_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id'),
    sa.UniqueConstraint('user_id', 'recurrence_series_id', 'date', name='uq_expense_series_date')
    )
    op.create_index(op.f('ix_expenses_expense_id'), 'expenses', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expenses_recurrence_series_id'), 'expenses', ['recurrence_series_id'], unique=False)
    op.create_table('income',
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bulk', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('preferred_currency_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('usd_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recurrence_series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recurrence_series_id'], ['recurrence_series.series_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('income_id'),
    sa.UniqueConstraint('user_id', 'recurrence_series_id', 'date', name='uq_income_series_date')
    )
    op.create_index(op.f('ix_income_income_id'), 'income', ['income_id'], unique=False)
    op.create_index(op.f('ix_income_recurrence_series_id'), 'income', ['recurrence_series_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('billing_customer_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_item_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIAL', 'CANCELLED', 'EXPIRED', name='subscription_status'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_income_recurrence_series_id'), table_name='income')
    op.drop_index(op.f('ix_income_income_id'), table_name='income')
    op.drop_table('income')
    op.drop_index(op.f('ix_expenses_recurrence_series_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('user_insight_prefs')
    op.drop_index(op.f('ix_recurrence_series_series_id'), table_name='recurrence_series')
    op.drop_table('recurrence_series')
    op.drop_index(op.f('ix_insights_insight_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_forecasts_forecast_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_billing_customers_id'), table_name='billing_customers')
    op.drop_table('billing_customers')
    op.drop_index(op.f('ix_webhook_events_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_insight_classes_name'), table_name='insight_classes')
    op.drop_index(op.f('ix_insight_classes_insight_class_id'), table_name='insight_classes')
    op.drop_table('insight_classes')
    # ### end Alembic commands ###
